apiVersion: v1
kind: Pod
metadata:
 name:  fortune2s
spec:
 containers:
 - image: josephassiga/fortune:args
   name: html-generator
   args: ["2"]
   volumeMounts:
   - name: html
     mountPath: /var/htdocs
 - image: nginx:1.15.3-alpine
   name: web-server
   volumeMounts:
   - name: html
     mountPath: /usr/share/ngnix/html
     readOnly: true
   ports:
   - containerPort: 80
     protocol: TCP
 volumes:
  - name: html
    emptyDir: {}
