apiVersion: v1
kind: Pod
metadata:
   name: fortune
spec:
  containers:
  - image: josephassiga/fortune
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:1.15.3-alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/ngnix/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
