apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: josephassiga/kubia
    name: kubia-joseph
    ports:
    - containerPort: 8082
      protocol: TCP
